version: '3'

services:
  db:
    image: postgres:10.5
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - database_network
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  redis:
    image: redis:4.0.11
    networks:
      - redis_network

  nginx:
    image: nginx:1.15.5-alpine
    ports:
      # Will be available @ localhost:80
      #- "80:80"
      - "8083:80"
    depends_on:
      # Make sure Django's built so Nginx can serve its static content
      - django
    volumes:
      # Django's static files
      - static_files_volume:/usr/share/nginx/html/static
      # Nginx config
      - ./_app/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx_network

  django:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DJANGO_SECRET_KEY
    depends_on:
      - db
      - redis
    command: /bin/bash -c /usr/src/app/startapp.sh
    volumes:
      - ./_app:/usr/src/app
      # Django static files will go here so Nginx can access them
      - static_files_volume:/usr/src/app/static
    networks:
      - nginx_network
      - database_network
      - redis_network
    environment:
      - PYTHONUNBUFFERED=0
      - DJANGO_SECRET_KEY
      - POSTGRES_USER
      - POSTGRES_PASSWORD

volumes:
  static_files_volume:
  database_volume:

networks:
  nginx_network:
  database_network:
  redis_network:
